export const GAME_CONFIG = {
  LANE_WIDTH: 9,
  ROAD_SEGMENT_LENGTH: 10,
  MAX_SPEED_KMH: 220,
  MAX_SPEED_MS: 220 / 3.6,
  ACCELERATION: 15,
  BRAKE_FORCE: 25,
  DRIFT_ASSIST: 0.92,
  OFF_ROAD_SLOWDOWN: 0.5,
  CRASH_SPEED_THRESHOLD: 150,
  CURVE_FREQUENCY_BASE: 0.15,
  CURVE_FREQUENCY_INCREASE: 0.02,
  OBSTACLE_DENSITY_BASE: 0.05,
  OBSTACLE_DENSITY_INCREASE: 0.01,
  DIFFICULTY_RAMP_INTERVAL: 30000,
  HIT_RADIUS: 1.5,
} as const;

export const DREAM_NEXUS_COLORS = {
  navy: "#0E1B24",
  cyan: "#24A0CE",
  warm: "#FDC6B5",
  white: "#FFFFFF",
  roadGray: "#3a3a3a",
  roadLine: "#FFD700",
} as const;
